name = "8gpi-website"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-09-16"

[build]
  command = "npm run build && npx @cloudflare/next-on-pages"
  publish = ".vercel/output/static"

[site]
  bucket = ".vercel/output/static"
  entry-point = ".vercel/output/static"

[build.upload]
  format = "service-worker"
  main = ".vercel/output/static/_worker.js/index.js"

[env.production]
  name = "8gpi-website-prod"

# Environment variables
# These should be set in your Cloudflare Pages dashboard
# [vars]
# RESEND_API_KEY = ""
# NEXT_PUBLIC_EMAIL_RECIPIENT = ""
