name = "8gpi-website"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
  command = "npm run build && npx @cloudflare/next-on-pages"
  publish = ".vercel/output/static"
  format = "service-worker"

[site]
  bucket = ".vercel/output/static"
  entry-point = ".vercel/output/static"
  exclude = [
    "cache/**/*",
    "node_modules/**/*",
    "**/.*",
    "**/package-lock.json",
    "**/yarn.lock"
  ]

[env.production]
  name = "8gpi-website-prod"
  route = ""
  zone_id = ""

# Environment variables
# These should be set in your Cloudflare Pages dashboard
# [vars]
# RESEND_API_KEY = ""
# NEXT_PUBLIC_EMAIL_RECIPIENT = ""
