name = "8gpi-website"
compatibility_date = "2023-10-02"

# For static site deployment
[site]
bucket = ".vercel/output/static"
entry-point = ".vercel/output/static"

# Environment variables
# These should be set in your Cloudflare Pages dashboard
# [vars]
# RESEND_API_KEY = ""
# NEXT_PUBLIC_EMAIL_RECIPIENT = ""
