name = "8gpi-website"
compatibility_date = "2023-10-02"
main = "_worker.js"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build && npx @cloudflare/next-on-pages"
publish = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

# Environment variables
# These should be set in your Cloudflare Pages dashboard
# [vars]
# RESEND_API_KEY = ""
# NEXT_PUBLIC_EMAIL_RECIPIENT = ""
