name = "8gpi-website"
compatibility_date = "2023-10-02"
main = "_worker.js"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run deploy"
publish = ".vercel/static"

# Environment variables
# These should be set in your Cloudflare Pages dashboard
# [vars]
# RESEND_API_KEY = ""
# NEXT_PUBLIC_EMAIL_RECIPIENT = ""
