name = "8gpi-website"
main = ".open-next/server-function.cjs"
compatibility_date = "2025-09-16"

[build]
  command = "npm run build && npx open-next@latest build"
  cwd = "."

compatibility_flags = ["nodejs_compat"]

[site]
  bucket = ".open-next/static-files"

[env.production]
  name = "8gpi-website-prod"

# Environment variables
# These should be set in your Cloudflare Pages dashboard
# [vars]
# RESEND_API_KEY = ""
# NEXT_PUBLIC_EMAIL_RECIPIENT = ""

# Disable observability logs
[observability.logs]
enabled = false
